stages:
  define_dataset:
    cmd: python define_dataset.py ../data ./data
    deps:
      - ../data
    outs:
      - ./data
  train_model:
    cmd: python train_model.py ./data model.txt
    deps:
      - ./data
    outs:
      - model.txt
